### ISSUE TITLE
Chapter 5 / audio_clustering.py - bregman with python3

### ISSUE THREAD

**Issue by pallogu** [PacktPublishing/Predictive-Analytics-with-TensorFlow#1]
Hello,

I am trying to run audio_clustering.py with python3. However, I could not find bregman package for python3. Would you happen to have link of how to get the package?

Thanks a lot

**Comment by rezacsedu** [comment]
@pallogu the bregman package is not available in Python 3 so you'd try with Python 2.7+. 

See more at https://github.com/bregmanstudio/BregmanToolkit.
